frequency: 24 # update every x hours (be nice!)
list_header: False # Not implemented
list_metrics: False # Not implemented
configz_enabled: False # show running config at /configz
metricsz_enabled: True # provide prometheus compatible metrics via /metricsz (only supported when running via wsgi (i.e. in our default docker img)
memcached_server: false # set to memcached host to enable
combinations:
  standard:
    whitelists:
      - https://zebpalmer.github.io/dns_blocklists/whitelist.txt
    blocklists:
      - https://zebpalmer.github.io/dns_blocklists/slim.txt
      - https://zebpalmer.github.io/dns_blocklists/blocklist.txt
  slim:
    whitelists:
      - https://zebpalmer.github.io/dns_blocklists/whitelist.txt
    blocklists:
      - https://zebpalmer.github.io/dns_blocklists/slim.txt
